name: Defect Prediction Analysis

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  defect-analysis:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Install SpotBugs via Homebrew
        run: |
          if ! command -v spotbugs &> /dev/null; then
            brew update
            brew install spotbugs
          else
            echo "SpotBugs already installed."
          fi

      - name: Install cppcheck via Homebrew
        run: |
          if ! command -v cppcheck &> /dev/null; then
            brew update
            brew install cppcheck
          else
            echo "cppcheck already installed."
          fi

      - name: Run Defect Prediction Analysis
        run: python scripts/defect_prediction.py
